// GENERATED by Scripts/gen-glyphs.py. Do not edit.
//
// Sources (sha256 verified by the script):
//   Bravura 1.482 metadata: steinbergmedia/bravura @ 37b194378b710cc40e406ab6c4b07608bb9548ae
//     https://raw.githubusercontent.com/steinbergmedia/bravura/37b194378b710cc40e406ab6c4b07608bb9548ae/redist/Bravura.json
//     sha256 489fb4d734fc0b72a3cc601b50ebdf0bf8c57802ab9893e52ce030b86bf2ce11
//   SMuFL glyph names: w3c/smufl @ 9b720256048e98894e65eb01d6c1c4917f15efb7
//     https://raw.githubusercontent.com/w3c/smufl/9b720256048e98894e65eb01d6c1c4917f15efb7/metadata/glyphnames.json
//     sha256 cb72889c5f1fe470ac939a7f2c8c62f80b89e875d4eda8153027a372cb8ac531
//
// The bounding boxes, anchors and engraving defaults below are Bravura metadata,
// Copyright (c) Steinberg Media Technologies GmbH, with Reserved Font Name "Bravura",
// licensed under the SIL Open Font License 1.1: see Licenses/OFL-Bravura.txt.

import Foundation
#if canImport(CoreGraphics)
import CoreGraphics
#endif

/// A SMuFL glyph that the engraver uses. The raw value is the Unicode code point.
/// Metrics are in staff spaces for a font whose em is 4 staff spaces, y up from the
/// glyph origin (the baseline-left point), as SMuFL defines them.
public enum Glyph: UInt32, Sendable, Hashable, CaseIterable {
    case gClef = 0xE050
    case gClef15mb = 0xE051
    case gClef8vb = 0xE052
    case gClef8va = 0xE053
    case gClef15ma = 0xE054
    case fClef = 0xE062
    case fClef15mb = 0xE063
    case fClef8vb = 0xE064
    case fClef8va = 0xE065
    case fClef15ma = 0xE066
    case cClef = 0xE05C
    case cClef8vb = 0xE05D
    case unpitchedPercussionClef1 = 0xE069
    case sixStringTabClef = 0xE06D
    case timeSig0 = 0xE080
    case timeSig1 = 0xE081
    case timeSig2 = 0xE082
    case timeSig3 = 0xE083
    case timeSig4 = 0xE084
    case timeSig5 = 0xE085
    case timeSig6 = 0xE086
    case timeSig7 = 0xE087
    case timeSig8 = 0xE088
    case timeSig9 = 0xE089
    case timeSigCommon = 0xE08A
    case timeSigCutCommon = 0xE08B
    case noteheadDoubleWhole = 0xE0A0
    case noteheadWhole = 0xE0A2
    case noteheadHalf = 0xE0A3
    case noteheadBlack = 0xE0A4
    case noteheadXBlack = 0xE0A9
    case accidentalFlat = 0xE260
    case accidentalNatural = 0xE261
    case accidentalSharp = 0xE262
    case accidentalDoubleSharp = 0xE263
    case accidentalDoubleFlat = 0xE264
    case accidentalParensLeft = 0xE26A
    case accidentalParensRight = 0xE26B
    case restDoubleWhole = 0xE4E2
    case restWhole = 0xE4E3
    case restHalf = 0xE4E4
    case restQuarter = 0xE4E5
    case rest8th = 0xE4E6
    case rest16th = 0xE4E7
    case rest32nd = 0xE4E8
    case rest64th = 0xE4E9
    case rest128th = 0xE4EA
    case augmentationDot = 0xE1E7
    case repeatDot = 0xE044
    case brace = 0xE000
    case bracket = 0xE002
    case bracketTop = 0xE003
    case bracketBottom = 0xE004
    case flag8thUp = 0xE240
    case flag8thDown = 0xE241
    case flag16thUp = 0xE242
    case flag16thDown = 0xE243
    case flag32ndUp = 0xE244
    case flag32ndDown = 0xE245
    case flag64thUp = 0xE246
    case flag64thDown = 0xE247
    case flag128thUp = 0xE248
    case flag128thDown = 0xE249
    case fingering0 = 0xED10
    case fingering1 = 0xED11
    case fingering2 = 0xED12
    case fingering3 = 0xED13
    case fingering4 = 0xED14
    case fingering5 = 0xED15
    case tuplet0 = 0xE880
    case tuplet1 = 0xE881
    case tuplet2 = 0xE882
    case tuplet3 = 0xE883
    case tuplet4 = 0xE884
    case tuplet5 = 0xE885
    case tuplet6 = 0xE886
    case tuplet7 = 0xE887
    case tuplet8 = 0xE888
    case tuplet9 = 0xE889
    case segno = 0xE047
    case coda = 0xE048
    case metNoteWhole = 0xECA2
    case metNoteHalfUp = 0xECA3
    case metNoteQuarterUp = 0xECA5
    case metNote8thUp = 0xECA7
    case metNote16thUp = 0xECA9
    case metAugmentationDot = 0xECB7
    case dynamicPiano = 0xE520
    case dynamicMezzo = 0xE521
    case dynamicForte = 0xE522
    case dynamicRinforzando = 0xE523
    case dynamicSforzando = 0xE524
    case dynamicZ = 0xE525
    case dynamicNiente = 0xE526
    case dynamicPP = 0xE52B
    case dynamicPPP = 0xE52A
    case dynamicPPPP = 0xE529
    case dynamicMP = 0xE52C
    case dynamicMF = 0xE52D
    case dynamicPF = 0xE52E
    case dynamicFF = 0xE52F
    case dynamicFFF = 0xE530
    case dynamicFFFF = 0xE531
    case dynamicFortePiano = 0xE534
    case dynamicForzando = 0xE535
    case dynamicSforzando1 = 0xE536
    case dynamicSforzandoPiano = 0xE537
    case dynamicSforzandoPianissimo = 0xE538
    case dynamicSforzato = 0xE539
    case dynamicSforzatoPiano = 0xE53A
    case dynamicSforzatoFF = 0xE53B
    case dynamicRinforzando1 = 0xE53C
    case dynamicRinforzando2 = 0xE53D
    case keyboardPedalPed = 0xE650
    case keyboardPedalUp = 0xE655
    case ottavaAlta = 0xE511
    case ottavaBassaVb = 0xE51C
    case quindicesimaAlta = 0xE515
    case quindicesimaBassaMb = 0xE51D
    case ventiduesimaAlta = 0xE518
    case ventiduesimaBassaMb = 0xE51E
    case octaveParensLeft = 0xE51A
    case octaveParensRight = 0xE51B
}

extension Glyph {
    /// The metrics of this glyph in the bundled Bravura.
    public var metrics: GlyphMetrics { Glyph.table[self]! }

    private static let table: [Glyph: GlyphMetrics] = [
        .gClef: GlyphMetrics(minX: 0.0, minY: -2.632, maxX: 2.684, maxY: 4.392, advance: 2.684, anchors: [:]),
        .gClef15mb: GlyphMetrics(minX: 0.0, minY: -3.524, maxX: 2.684, maxY: 4.392, advance: 2.684, anchors: [:]),
        .gClef8vb: GlyphMetrics(minX: 0.0, minY: -3.512, maxX: 2.684, maxY: 4.392, advance: 2.656, anchors: [:]),
        .gClef8va: GlyphMetrics(minX: 0.0, minY: -2.632, maxX: 2.684, maxY: 5.28, advance: 2.684, anchors: [:]),
        .gClef15ma: GlyphMetrics(minX: 0.0, minY: -2.632, maxX: 2.684, maxY: 5.276, advance: 2.684, anchors: [:]),
        .fClef: GlyphMetrics(minX: -0.02, minY: -2.54, maxX: 2.736, maxY: 1.048, advance: 2.736, anchors: [:]),
        .fClef15mb: GlyphMetrics(minX: -0.02, minY: -2.968, maxX: 2.736, maxY: 1.048, advance: 2.736, anchors: [:]),
        .fClef8vb: GlyphMetrics(minX: -0.02, minY: -2.976, maxX: 2.736, maxY: 1.048, advance: 2.736, anchors: [:]),
        .fClef8va: GlyphMetrics(minX: -0.02, minY: -2.54, maxX: 2.736, maxY: 1.98, advance: 2.736, anchors: [:]),
        .fClef15ma: GlyphMetrics(minX: -0.02, minY: -2.54, maxX: 2.736, maxY: 1.984, advance: 2.736, anchors: [:]),
        .cClef: GlyphMetrics(minX: 0.0, minY: -2.024, maxX: 2.796, maxY: 2.024, advance: 2.796, anchors: [:]),
        .cClef8vb: GlyphMetrics(minX: 0.0, minY: -2.964, maxX: 2.796, maxY: 2.024, advance: 2.796, anchors: [:]),
        .unpitchedPercussionClef1: GlyphMetrics(minX: 0.0, minY: -1.0, maxX: 1.528, maxY: 1.0, advance: 1.528, anchors: [:]),
        .sixStringTabClef: GlyphMetrics(minX: -0.012, minY: -2.992, maxX: 1.632, maxY: 3.056, advance: 1.636, anchors: [:]),
        .timeSig0: GlyphMetrics(minX: 0.08, minY: -1.0, maxX: 1.8, maxY: 1.004, advance: 1.88, anchors: [:]),
        .timeSig1: GlyphMetrics(minX: 0.08, minY: -1.0, maxX: 1.256, maxY: 1.004, advance: 1.336, anchors: [:]),
        .timeSig2: GlyphMetrics(minX: 0.08, minY: -1.028, maxX: 1.704, maxY: 1.016, advance: 1.784, anchors: [:]),
        .timeSig3: GlyphMetrics(minX: 0.08, minY: -1.004, maxX: 1.604, maxY: 0.996, advance: 1.684, anchors: [:]),
        .timeSig4: GlyphMetrics(minX: 0.08, minY: -1.0, maxX: 1.8, maxY: 1.004, advance: 1.88, anchors: [:]),
        .timeSig5: GlyphMetrics(minX: 0.08, minY: -1.004, maxX: 1.532, maxY: 0.984, advance: 1.612, anchors: [:]),
        .timeSig6: GlyphMetrics(minX: 0.08, minY: -0.996, maxX: 1.656, maxY: 1.004, advance: 1.736, anchors: [:]),
        .timeSig7: GlyphMetrics(minX: 0.08, minY: -1.0, maxX: 1.684, maxY: 0.996, advance: 1.764, anchors: [:]),
        .timeSig8: GlyphMetrics(minX: 0.08, minY: -1.036, maxX: 1.664, maxY: 1.036, advance: 1.744, anchors: [:]),
        .timeSig9: GlyphMetrics(minX: 0.08, minY: -0.996, maxX: 1.656, maxY: 1.004, advance: 1.736, anchors: [:]),
        .timeSigCommon: GlyphMetrics(minX: 0.02, minY: -0.996, maxX: 1.696, maxY: 1.004, advance: 1.696, anchors: [:]),
        .timeSigCutCommon: GlyphMetrics(minX: 0.0, minY: -1.436, maxX: 1.672, maxY: 1.444, advance: 1.668, anchors: [:]),
        .noteheadDoubleWhole: GlyphMetrics(minX: 0.0, minY: -0.62, maxX: 2.396, maxY: 0.62, advance: 2.396, anchors: ["stemDownNW": CGPoint(x: 0.36, y: 0.004), "stemUpSE": CGPoint(x: 2.036, y: 0.004)]),
        .noteheadWhole: GlyphMetrics(minX: 0.0, minY: -0.5, maxX: 1.688, maxY: 0.5, advance: 1.688, anchors: [:]),
        .noteheadHalf: GlyphMetrics(minX: 0.0, minY: -0.5, maxX: 1.18, maxY: 0.5, advance: 1.18, anchors: ["stemDownNW": CGPoint(x: 0.0, y: -0.168), "stemUpSE": CGPoint(x: 1.18, y: 0.168)]),
        .noteheadBlack: GlyphMetrics(minX: 0.0, minY: -0.5, maxX: 1.18, maxY: 0.5, advance: 1.18, anchors: ["stemDownNW": CGPoint(x: 0.0, y: -0.168), "stemUpSE": CGPoint(x: 1.18, y: 0.168)]),
        .noteheadXBlack: GlyphMetrics(minX: 0.0, minY: -0.5, maxX: 1.16, maxY: 0.5, advance: 1.16, anchors: ["stemDownNW": CGPoint(x: 0.0, y: -0.44), "stemUpSE": CGPoint(x: 1.16, y: 0.444)]),
        .accidentalFlat: GlyphMetrics(minX: 0.0, minY: -0.7, maxX: 0.904, maxY: 1.756, advance: 0.904, anchors: [:]),
        .accidentalNatural: GlyphMetrics(minX: 0.0, minY: -1.34, maxX: 0.672, maxY: 1.364, advance: 0.672, anchors: [:]),
        .accidentalSharp: GlyphMetrics(minX: 0.0, minY: -1.392, maxX: 0.996, maxY: 1.4, advance: 0.996, anchors: [:]),
        .accidentalDoubleSharp: GlyphMetrics(minX: 0.0, minY: -0.5, maxX: 0.988, maxY: 0.508, advance: 1.0, anchors: [:]),
        .accidentalDoubleFlat: GlyphMetrics(minX: 0.0, minY: -0.7, maxX: 1.644, maxY: 1.748, advance: 1.652, anchors: [:]),
        .accidentalParensLeft: GlyphMetrics(minX: 0.0, minY: -0.992, maxX: 0.564, maxY: 0.988, advance: 0.564, anchors: [:]),
        .accidentalParensRight: GlyphMetrics(minX: 0.0, minY: -0.992, maxX: 0.564, maxY: 0.988, advance: 0.564, anchors: [:]),
        .restDoubleWhole: GlyphMetrics(minX: 0.0, minY: 0.0, maxX: 0.5, maxY: 1.0, advance: 0.504, anchors: [:]),
        .restWhole: GlyphMetrics(minX: 0.0, minY: -0.54, maxX: 1.128, maxY: 0.036, advance: 1.132, anchors: [:]),
        .restHalf: GlyphMetrics(minX: 0.0, minY: -0.008, maxX: 1.128, maxY: 0.568, advance: 1.132, anchors: [:]),
        .restQuarter: GlyphMetrics(minX: 0.004, minY: -1.5, maxX: 1.08, maxY: 1.492, advance: 1.08, anchors: [:]),
        .rest8th: GlyphMetrics(minX: 0.0, minY: -1.004, maxX: 0.988, maxY: 0.696, advance: 1.0, anchors: [:]),
        .rest16th: GlyphMetrics(minX: 0.0, minY: -2.0, maxX: 1.28, maxY: 0.716, advance: 1.28, anchors: [:]),
        .rest32nd: GlyphMetrics(minX: 0.0, minY: -2.0, maxX: 1.452, maxY: 1.704, advance: 1.452, anchors: [:]),
        .rest64th: GlyphMetrics(minX: 0.0, minY: -3.012, maxX: 1.692, maxY: 1.72, advance: 1.696, anchors: [:]),
        .rest128th: GlyphMetrics(minX: 0.0, minY: -3.0, maxX: 1.94, maxY: 2.756, advance: 1.94, anchors: [:]),
        .augmentationDot: GlyphMetrics(minX: 0.0, minY: -0.2, maxX: 0.4, maxY: 0.2, advance: 0.4, anchors: [:]),
        .repeatDot: GlyphMetrics(minX: 0.0, minY: -0.2, maxX: 0.4, maxY: 0.2, advance: 0.4, anchors: [:]),
        .brace: GlyphMetrics(minX: 0.0, minY: -0.0025, maxX: 0.2774, maxY: 4.0024, advance: 0.28, anchors: [:]),
        .bracket: GlyphMetrics(minX: 0.0, minY: -1.272, maxX: 1.876, maxY: 5.284, advance: 2.232, anchors: [:]),
        .bracketTop: GlyphMetrics(minX: 0.0, minY: 0.0, maxX: 1.876, maxY: 1.18, advance: 1.876, anchors: [:]),
        .bracketBottom: GlyphMetrics(minX: 0.0, minY: -1.18, maxX: 1.876, maxY: 0.0, advance: 1.876, anchors: [:]),
        .flag8thUp: GlyphMetrics(minX: 0.0, minY: -3.24, maxX: 1.056, maxY: 0.036, advance: 1.056, anchors: ["stemUpNW": CGPoint(x: 0.0, y: -0.04)]),
        .flag8thDown: GlyphMetrics(minX: 0.0, minY: -0.056, maxX: 1.224, maxY: 3.232, advance: 1.224, anchors: ["stemDownSW": CGPoint(x: 0.0, y: 0.132)]),
        .flag16thUp: GlyphMetrics(minX: 0.0, minY: -3.252, maxX: 1.116, maxY: 0.008, advance: 1.116, anchors: ["stemUpNW": CGPoint(x: 0.0, y: -0.088)]),
        .flag16thDown: GlyphMetrics(minX: 0.0, minY: -0.036, maxX: 1.164, maxY: 3.248, advance: 1.168, anchors: ["stemDownSW": CGPoint(x: 0.0, y: 0.128)]),
        .flag32ndUp: GlyphMetrics(minX: 0.0, minY: -3.248, maxX: 1.044, maxY: 0.596, advance: 1.048, anchors: ["stemUpNW": CGPoint(x: 0.0, y: 0.376)]),
        .flag32ndDown: GlyphMetrics(minX: 0.0, minY: -0.688, maxX: 1.092, maxY: 3.248, advance: 1.096, anchors: ["stemDownSW": CGPoint(x: 0.0, y: -0.448)]),
        .flag64thUp: GlyphMetrics(minX: 0.0, minY: -3.248, maxX: 1.044, maxY: 1.388, advance: 1.048, anchors: ["stemUpNW": CGPoint(x: 0.0, y: 1.172)]),
        .flag64thDown: GlyphMetrics(minX: 0.0, minY: -1.504, maxX: 1.092, maxY: 3.248, advance: 1.1, anchors: ["stemDownSW": CGPoint(x: 0.0, y: -1.244)]),
        .flag128thUp: GlyphMetrics(minX: 0.0, minY: -3.248, maxX: 1.044, maxY: 2.132, advance: 1.036, anchors: ["stemUpNW": CGPoint(x: 0.0, y: 1.9)]),
        .flag128thDown: GlyphMetrics(minX: 0.0, minY: -2.32, maxX: 1.092, maxY: 3.248, advance: 1.1, anchors: ["stemDownSW": CGPoint(x: 0.0, y: -2.076)]),
        .fingering0: GlyphMetrics(minX: 0.08, minY: -0.004, maxX: 0.94, maxY: 1.004, advance: 1.02, anchors: [:]),
        .fingering1: GlyphMetrics(minX: 0.08, minY: 0.0, maxX: 0.548, maxY: 1.016, advance: 0.628, anchors: [:]),
        .fingering2: GlyphMetrics(minX: 0.08, minY: -0.012, maxX: 0.888, maxY: 1.012, advance: 0.968, anchors: [:]),
        .fingering3: GlyphMetrics(minX: 0.08, minY: 0.0, maxX: 0.82, maxY: 1.008, advance: 0.9, anchors: [:]),
        .fingering4: GlyphMetrics(minX: 0.08, minY: 0.004, maxX: 0.864, maxY: 1.012, advance: 0.944, anchors: [:]),
        .fingering5: GlyphMetrics(minX: 0.08, minY: 0.0, maxX: 0.82, maxY: 1.032, advance: 0.9, anchors: [:]),
        .tuplet0: GlyphMetrics(minX: 0.0, minY: -0.032, maxX: 1.272, maxY: 1.5, advance: 1.276, anchors: [:]),
        .tuplet1: GlyphMetrics(minX: 0.04, minY: 0.0, maxX: 1.024, maxY: 1.488, advance: 0.984, anchors: [:]),
        .tuplet2: GlyphMetrics(minX: 0.04, minY: -0.024, maxX: 1.316, maxY: 1.5, advance: 1.276, anchors: [:]),
        .tuplet3: GlyphMetrics(minX: 0.04, minY: -0.032, maxX: 1.224, maxY: 1.5, advance: 1.184, anchors: [:]),
        .tuplet4: GlyphMetrics(minX: 0.04, minY: 0.0, maxX: 1.252, maxY: 1.488, advance: 1.212, anchors: [:]),
        .tuplet5: GlyphMetrics(minX: 0.04, minY: -0.032, maxX: 1.308, maxY: 1.492, advance: 1.268, anchors: [:]),
        .tuplet6: GlyphMetrics(minX: 0.04, minY: -0.032, maxX: 1.256, maxY: 1.5, advance: 1.216, anchors: [:]),
        .tuplet7: GlyphMetrics(minX: 0.12, minY: -0.016, maxX: 1.332, maxY: 1.488, advance: 1.212, anchors: [:]),
        .tuplet8: GlyphMetrics(minX: 0.04, minY: -0.032, maxX: 1.292, maxY: 1.5, advance: 1.252, anchors: [:]),
        .tuplet9: GlyphMetrics(minX: 0.04, minY: -0.032, maxX: 1.256, maxY: 1.5, advance: 1.216, anchors: [:]),
        .segno: GlyphMetrics(minX: 0.016, minY: -0.108, maxX: 2.2, maxY: 3.036, advance: 2.228, anchors: [:]),
        .coda: GlyphMetrics(minX: -0.016, minY: -0.632, maxX: 3.82, maxY: 3.592, advance: 3.816, anchors: [:]),
        .metNoteWhole: GlyphMetrics(minX: 0.0, minY: -0.5, maxX: 1.836, maxY: 0.592, advance: 1.836, anchors: [:]),
        .metNoteHalfUp: GlyphMetrics(minX: 0.0, minY: -0.564, maxX: 1.364, maxY: 2.752, advance: 1.364, anchors: [:]),
        .metNoteQuarterUp: GlyphMetrics(minX: 0.0, minY: -0.564, maxX: 1.328, maxY: 2.752, advance: 1.328, anchors: [:]),
        .metNote8thUp: GlyphMetrics(minX: 0.0, minY: -0.564, maxX: 2.132, maxY: 2.784, advance: 2.136, anchors: [:]),
        .metNote16thUp: GlyphMetrics(minX: 0.0, minY: -0.564, maxX: 2.084, maxY: 2.8, advance: 2.088, anchors: [:]),
        .metAugmentationDot: GlyphMetrics(minX: 0.0, minY: -0.2, maxX: 0.4, maxY: 0.2, advance: 0.4, anchors: [:]),
        .dynamicPiano: GlyphMetrics(minX: -0.356, minY: -0.568, maxX: 1.464, maxY: 1.096, advance: 1.46, anchors: ["opticalCenter": CGPoint(x: 1.22, y: 0.0)]),
        .dynamicMezzo: GlyphMetrics(minX: -0.08, minY: -0.04, maxX: 1.784, maxY: 1.096, advance: 1.748, anchors: ["opticalCenter": CGPoint(x: 0.872, y: 0.0)]),
        .dynamicForte: GlyphMetrics(minX: -0.564, minY: -0.608, maxX: 1.456, maxY: 1.776, advance: 1.456, anchors: ["opticalCenter": CGPoint(x: 1.256, y: 0.0)]),
        .dynamicRinforzando: GlyphMetrics(minX: -0.08, minY: 0.0, maxX: 1.108, maxY: 1.096, advance: 1.108, anchors: ["opticalCenter": CGPoint(x: 0.612, y: 0.0)]),
        .dynamicSforzando: GlyphMetrics(minX: 0.0, minY: -0.04, maxX: 0.916, maxY: 1.092, advance: 0.916, anchors: ["opticalCenter": CGPoint(x: 0.444, y: 0.0)]),
        .dynamicZ: GlyphMetrics(minX: -0.12, minY: -0.04, maxX: 0.976, maxY: 1.072, advance: 0.976, anchors: ["opticalCenter": CGPoint(x: 0.5, y: 0.0)]),
        .dynamicNiente: GlyphMetrics(minX: -0.092, minY: -0.04, maxX: 1.232, maxY: 1.096, advance: 1.232, anchors: ["opticalCenter": CGPoint(x: 0.616, y: 0.0)]),
        .dynamicPP: GlyphMetrics(minX: -0.328, minY: -0.568, maxX: 2.912, maxY: 1.096, advance: 2.908, anchors: ["opticalCenter": CGPoint(x: 1.708, y: 0.0)]),
        .dynamicPPP: GlyphMetrics(minX: -0.368, minY: -0.568, maxX: 4.292, maxY: 1.096, advance: 4.288, anchors: ["opticalCenter": CGPoint(x: 2.368, y: 0.0)]),
        .dynamicPPPP: GlyphMetrics(minX: -0.408, minY: -0.568, maxX: 5.672, maxY: 1.096, advance: 5.668, anchors: ["opticalCenter": CGPoint(x: 3.004, y: 0.0)]),
        .dynamicMP: GlyphMetrics(minX: -0.08, minY: -0.568, maxX: 3.3, maxY: 1.096, advance: 3.304, anchors: ["opticalCenter": CGPoint(x: 1.848, y: 0.0)]),
        .dynamicMF: GlyphMetrics(minX: -0.08, minY: -0.66, maxX: 3.272, maxY: 1.724, advance: 3.188, anchors: ["opticalCenter": CGPoint(x: 1.796, y: 0.0)]),
        .dynamicPF: GlyphMetrics(minX: -0.288, minY: -0.608, maxX: 3.08, maxY: 1.776, advance: 3.08, anchors: ["opticalCenter": CGPoint(x: 1.68, y: 0.0)]),
        .dynamicFF: GlyphMetrics(minX: -0.54, minY: -0.608, maxX: 2.44, maxY: 1.776, advance: 2.436, anchors: ["opticalCenter": CGPoint(x: 1.852, y: 0.0)]),
        .dynamicFFF: GlyphMetrics(minX: -0.62, minY: -0.608, maxX: 3.32, maxY: 1.776, advance: 3.324, anchors: ["opticalCenter": CGPoint(x: 2.472, y: 0.0)]),
        .dynamicFFFF: GlyphMetrics(minX: -0.62, minY: -0.608, maxX: 4.28, maxY: 1.776, advance: 4.28, anchors: ["opticalCenter": CGPoint(x: 2.824, y: 0.0)]),
        .dynamicFortePiano: GlyphMetrics(minX: -0.564, minY: -0.608, maxX: 2.476, maxY: 1.776, advance: 2.476, anchors: ["opticalCenter": CGPoint(x: 1.5, y: 0.0)]),
        .dynamicForzando: GlyphMetrics(minX: -0.564, minY: -0.608, maxX: 1.988, maxY: 1.776, advance: 1.988, anchors: ["opticalCenter": CGPoint(x: 1.352, y: 0.0)]),
        .dynamicSforzando1: GlyphMetrics(minX: 0.0, minY: -0.608, maxX: 2.416, maxY: 1.776, advance: 2.416, anchors: ["opticalCenter": CGPoint(x: 1.3, y: 0.0)]),
        .dynamicSforzandoPiano: GlyphMetrics(minX: 0.0, minY: -0.608, maxX: 3.38, maxY: 1.776, advance: 3.384, anchors: ["opticalCenter": CGPoint(x: 1.904, y: 0.0)]),
        .dynamicSforzandoPianissimo: GlyphMetrics(minX: 0.0, minY: -0.608, maxX: 4.796, maxY: 1.776, advance: 4.792, anchors: ["opticalCenter": CGPoint(x: 1.972, y: 0.0)]),
        .dynamicSforzato: GlyphMetrics(minX: 0.0, minY: -0.608, maxX: 2.932, maxY: 1.776, advance: 2.928, anchors: ["opticalCenter": CGPoint(x: 1.76, y: 0.0)]),
        .dynamicSforzatoPiano: GlyphMetrics(minX: 0.0, minY: -0.608, maxX: 4.304, maxY: 1.776, advance: 4.3, anchors: ["opticalCenter": CGPoint(x: 1.848, y: 0.0)]),
        .dynamicSforzatoFF: GlyphMetrics(minX: 0.0, minY: -0.608, maxX: 3.856, maxY: 1.776, advance: 3.856, anchors: ["opticalCenter": CGPoint(x: 2.276, y: 0.0)]),
        .dynamicRinforzando1: GlyphMetrics(minX: -0.08, minY: -0.608, maxX: 2.5, maxY: 1.776, advance: 2.5, anchors: ["opticalCenter": CGPoint(x: 1.564, y: 0.0)]),
        .dynamicRinforzando2: GlyphMetrics(minX: -0.08, minY: -0.608, maxX: 2.976, maxY: 1.776, advance: 2.976, anchors: ["opticalCenter": CGPoint(x: 2.084, y: 0.0)]),
        .keyboardPedalPed: GlyphMetrics(minX: 0.0, minY: -0.032, maxX: 4.076, maxY: 2.22, advance: 4.076, anchors: [:]),
        .keyboardPedalUp: GlyphMetrics(minX: 0.0, minY: 0.0, maxX: 1.8, maxY: 1.8, advance: 1.8, anchors: [:]),
        .ottavaAlta: GlyphMetrics(minX: 0.0, minY: -0.04, maxX: 3.54, maxY: 1.852, advance: 3.54, anchors: [:]),
        .ottavaBassaVb: GlyphMetrics(minX: 0.0, minY: -0.04, maxX: 3.184, maxY: 1.852, advance: 3.184, anchors: [:]),
        .quindicesimaAlta: GlyphMetrics(minX: 0.0, minY: -0.04, maxX: 5.26, maxY: 1.844, advance: 5.26, anchors: [:]),
        .quindicesimaBassaMb: GlyphMetrics(minX: 0.0, minY: -0.04, maxX: 4.928, maxY: 1.844, advance: 4.924, anchors: [:]),
        .ventiduesimaAlta: GlyphMetrics(minX: 0.016, minY: -0.028, maxX: 5.712, maxY: 1.852, advance: 5.712, anchors: [:]),
        .ventiduesimaBassaMb: GlyphMetrics(minX: 0.016, minY: -0.028, maxX: 5.34, maxY: 1.852, advance: 5.34, anchors: [:]),
        .octaveParensLeft: GlyphMetrics(minX: 0.0, minY: -0.068, maxX: 0.652, maxY: 1.936, advance: 0.548, anchors: [:]),
        .octaveParensRight: GlyphMetrics(minX: -0.104, minY: -0.068, maxX: 0.548, maxY: 1.936, advance: 0.548, anchors: [:]),
    ]
}

/// Bravura's `engravingDefaults`, in staff spaces.
public enum EngravingDefaults {
    public static let staffLineThickness: Double = 0.13
    public static let stemThickness: Double = 0.12
    public static let beamThickness: Double = 0.5
    public static let beamSpacing: Double = 0.25
    public static let legerLineThickness: Double = 0.16
    public static let legerLineExtension: Double = 0.4
    public static let thinBarlineThickness: Double = 0.16
    public static let thickBarlineThickness: Double = 0.5
    public static let barlineSeparation: Double = 0.4
    public static let thinThickBarlineSeparation: Double = 0.4
    public static let repeatBarlineDotSeparation: Double = 0.16
    public static let bracketThickness: Double = 0.5
    public static let subBracketThickness: Double = 0.16
    public static let slurEndpointThickness: Double = 0.1
    public static let slurMidpointThickness: Double = 0.22
    public static let tieEndpointThickness: Double = 0.1
    public static let tieMidpointThickness: Double = 0.22
    public static let tupletBracketThickness: Double = 0.16
    public static let repeatEndingLineThickness: Double = 0.16
    public static let hairpinThickness: Double = 0.16
    public static let octaveLineThickness: Double = 0.16
    public static let pedalLineThickness: Double = 0.16
}
