#!/usr/bin/env python3
"""Regenerate Sources/ScoreKit/Layout/Glyphs.swift from pinned upstream sources.

usage: Scripts/gen-glyphs.py > Sources/ScoreKit/Layout/Glyphs.swift

Downloads (and caches under .build/glyph-sources/) the Bravura SMuFL metadata and the SMuFL
glyph names at the pinned commits below, verifies their sha256, and prints the Swift file.
The Bravura commit is the one the app's bundled Bravura.otf (bravura-1.482) comes from.
"""
import hashlib, json, os, sys, urllib.request

BRAVURA_COMMIT = "37b194378b710cc40e406ab6c4b07608bb9548ae"  # steinbergmedia/bravura, tag bravura-1.482
SMUFL_COMMIT = "9b720256048e98894e65eb01d6c1c4917f15efb7"    # w3c/smufl, last change to glyphnames.json
SOURCES = {
    "Bravura.json": (f"https://raw.githubusercontent.com/steinbergmedia/bravura/{BRAVURA_COMMIT}/redist/Bravura.json",
                     "489fb4d734fc0b72a3cc601b50ebdf0bf8c57802ab9893e52ce030b86bf2ce11"),
    "glyphnames.json": (f"https://raw.githubusercontent.com/w3c/smufl/{SMUFL_COMMIT}/metadata/glyphnames.json",
                        "cb72889c5f1fe470ac939a7f2c8c62f80b89e875d4eda8153027a372cb8ac531"),
}

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
cache = os.path.join(root, ".build", "glyph-sources")
os.makedirs(cache, exist_ok=True)

def fetch(name):
    url, want = SOURCES[name]
    path = os.path.join(cache, name)
    if not os.path.exists(path):
        with urllib.request.urlopen(url) as r, open(path, "wb") as f:
            f.write(r.read())
    got = hashlib.sha256(open(path, "rb").read()).hexdigest()
    if got != want:
        sys.exit(f"{name}: sha256 {got} != pinned {want}")
    return json.load(open(path))

meta = fetch("Bravura.json")
names = fetch("glyphnames.json")

GLYPHS = """
gClef gClef15mb gClef8vb gClef8va gClef15ma fClef fClef15mb fClef8vb fClef8va fClef15ma
cClef cClef8vb unpitchedPercussionClef1 6stringTabClef
timeSig0 timeSig1 timeSig2 timeSig3 timeSig4 timeSig5 timeSig6 timeSig7 timeSig8 timeSig9
timeSigCommon timeSigCutCommon
noteheadDoubleWhole noteheadWhole noteheadHalf noteheadBlack noteheadXBlack
accidentalFlat accidentalNatural accidentalSharp accidentalDoubleSharp accidentalDoubleFlat
accidentalParensLeft accidentalParensRight
restDoubleWhole restWhole restHalf restQuarter rest8th rest16th rest32nd rest64th rest128th
augmentationDot repeatDot brace bracket bracketTop bracketBottom
flag8thUp flag8thDown flag16thUp flag16thDown flag32ndUp flag32ndDown flag64thUp flag64thDown
flag128thUp flag128thDown
fingering0 fingering1 fingering2 fingering3 fingering4 fingering5
tuplet0 tuplet1 tuplet2 tuplet3 tuplet4 tuplet5 tuplet6 tuplet7 tuplet8 tuplet9
segno coda
""".split()

def swift_name(n):
    return "sixStringTabClef" if n == "6stringTabClef" else n

def num(x):
    s = repr(round(x, 4))
    return s

out = []
out.append(f"""// GENERATED by Scripts/gen-glyphs.py. Do not edit.
//
// Sources (sha256 verified by the script):
//   Bravura {meta['fontVersion']} metadata: steinbergmedia/bravura @ {BRAVURA_COMMIT}
//     {SOURCES['Bravura.json'][0]}
//     sha256 {SOURCES['Bravura.json'][1]}
//   SMuFL glyph names: w3c/smufl @ {SMUFL_COMMIT}
//     {SOURCES['glyphnames.json'][0]}
//     sha256 {SOURCES['glyphnames.json'][1]}
//
// The bounding boxes, anchors and engraving defaults below are Bravura metadata,
// Copyright (c) Steinberg Media Technologies GmbH, with Reserved Font Name "Bravura",
// licensed under the SIL Open Font License 1.1: see Licenses/OFL-Bravura.txt.

import Foundation
#if canImport(CoreGraphics)
import CoreGraphics
#endif

/// A SMuFL glyph that the engraver uses. The raw value is the Unicode code point.
/// Metrics are in staff spaces for a font whose em is 4 staff spaces, y up from the
/// glyph origin (the baseline-left point), as SMuFL defines them.
public enum Glyph: UInt32, Sendable, Hashable, CaseIterable {{""")
for g in GLYPHS:
    cp = int(names[g]["codepoint"][2:], 16)
    out.append(f"    case {swift_name(g)} = 0x{cp:04X}")
out.append("}\n")
out.append("extension Glyph {")
out.append("    /// The metrics of this glyph in the bundled Bravura.")
out.append("    public var metrics: GlyphMetrics { Glyph.table[self]! }\n")
out.append("    private static let table: [Glyph: GlyphMetrics] = [")
for g in GLYPHS:
    bb = meta["glyphBBoxes"][g]
    sw, ne = bb["bBoxSW"], bb["bBoxNE"]
    adv = meta["glyphAdvanceWidths"][g]
    anchors = meta["glyphsWithAnchors"].get(g, {})
    keep = {k: v for k, v in anchors.items() if k in ("stemUpSE", "stemDownNW", "stemUpNW", "stemDownSW", "opticalCenter")}
    a = ", ".join(f'"{k}": CGPoint(x: {num(v[0])}, y: {num(v[1])})' for k, v in sorted(keep.items()))
    a = f"[{a}]" if a else "[:]"
    out.append(f"        .{swift_name(g)}: GlyphMetrics(minX: {num(sw[0])}, minY: {num(sw[1])}, maxX: {num(ne[0])}, maxY: {num(ne[1])}, advance: {num(adv)}, anchors: {a}),")
out.append("    ]")
out.append("}\n")
e = meta["engravingDefaults"]
out.append("/// Bravura's `engravingDefaults`, in staff spaces.")
out.append("public enum EngravingDefaults {")
for k in ["staffLineThickness", "stemThickness", "beamThickness", "beamSpacing", "legerLineThickness", "legerLineExtension",
          "thinBarlineThickness", "thickBarlineThickness", "barlineSeparation", "thinThickBarlineSeparation",
          "repeatBarlineDotSeparation", "bracketThickness", "subBracketThickness", "slurEndpointThickness",
          "slurMidpointThickness", "tieEndpointThickness", "tieMidpointThickness", "tupletBracketThickness",
          "repeatEndingLineThickness"]:
    out.append(f"    public static let {k}: Double = {num(e[k])}")
out.append("}")
print("\n".join(out))
